### ISSUE TITLE
Wrong version string for 15w14a

### ISSUE THREAD

**Issue by HowardZHY** [neoforged/SRGUtils#5]
https://github.com/neoforged/SRGUtils/blob/e521b119db7fb082608a19d1fdc64ae603ad9f31/src/main/java/net/neoforged/srgutils/MinecraftVersion.java#L95

return new MinecraftVersion(Type.APRIL_FOOLS, version, 14, 15, 0, "a", splitDots("1.8"));

**Comment by sciwhiz12** [comment]
Yeah, this looks incorrect. According to the Minecraft wiki (https://minecraft.wiki/w/Java_Edition_15w14a), while 15w14a was termed "1.10" in the Mojang blog post, it is actually a fork of 1.8.3.

I'll push a fix in a bit to correct that to `1.8.3`. Thanks for the report!
